AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  robrendellwebsitegeneratesudoku:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::882694435373:role/service-role/robrendellwebsite-generate-sudoku-role-x5f7qys8
      Environment:
        Variables:
          ACCESS_KEY: ---ENTER ACCESS KEY---
          API_SUDOKU_GEN_CALLBACK: /sudoku/add/callback
          API_URL: 'https://robrendellwebsite.herokuapp.com'
          SECRET_KEY: ---SECRET KEY---
          SUDOKU_GEN_SECURITY_KEY: ---SUDOKU-GEN-SECURITY-KEY---
      RuntimePolicy:
        UpdateRuntimeOn: Auto
